version: "3"

services:
  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - type: bind
        source: ./sounds
        target: /app/sounds
      - type: bind
        source: ./sounds.json
        target: /app/sounds.json
